### ISSUE TITLE
tradebeans/tradesoap in dacapo-23.8-chopin-RC1 fails with OpenJDK11 built from open source code

### ISSUE THREAD

**Issue by David-Raccoon** [dacapobench/dacapobench#225]
The version of Java:

```
openjdk version "11-internal" 2018-09-25
OpenJDK Runtime Environment (build 11-internal+0-adhoc..jdk)
OpenJDK 64-Bit Server VM (build 11-internal+0-adhoc..jdk, mixed mode)
```

The output when running tradebeans/tradesoap is here, and JVM dies silently several seconds at this point.

```
Using scaled threading model. 40 processors detected, 40 threads used to drive the workload, in a possible range of [1,2048]
Version: daytrader svn-1904225 wildfly 26.1.3
Nominal stats: GCA: 5|81, GCC: 7|1191, GCM: 5|83, GCP: 5|4, GLK: 8|28, GMH: 7|105, GMU: 7|151, GSS: 5|84, PET: 7|4, PPE: 2|3, PSD: 3|2, PWU: 8|1
Launching the server with timeout of 50 seconds (use -f to adjust timeout dialation).
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/home/ppi/whz/learning_based_jvm/./lib/dacapo-23.8-chopin-RC1/dat/lib/daytrader/wildfly-26.1.3.Final/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-18.1.2.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by steveblackburn** [comment]
The warnings are normal, a problem with the Wildfly upstream.

Are you able to reproduce this on any other jdk11, other than one you built yourself?

I test on stock JDK binaries on a number of platforms, and have not seen this.  If you can point me toward reproducibility with stock binaries that would help.

Also, please provide the exact command line you used when you saw it fail.

**Comment by David-Raccoon** [comment]
The jdk11 I built is from the OpenJDK github repository, without changing anything. The repo tag is jdk-11+19. My platform is ubuntu 18.04, x64. The build configurations for JDK are as follows.
```
./configure --with-target-bits=64 --with-debug-level=release --with-extra-cflags='-Wno-deprecated-declarations'
```

Other jdk11 (e.g., the one get from apt-get install openjdk-11-jdk on ubuntu 18.04) than the one I built from myself works fine. It outputs the same but JVM does not die in this way, and the execution continues normally.

The command line I use which causes this fail was normal:
```
java -jar dacapo-23.8-chopin-RC1.jar tradebeans
# or tradesoap
```
Did I use it correctly?

**Comment by steveblackburn** [comment]
Yes, you used it fine.  

It's possible that `--with-extra-cflags='-Wno-deprecated-declarations'` is the problem.  The upstream in the case of this benchmark (Wildfly) uses reflection which triggers JDK11 deprecation warnings (as in your post above).  Perhaps you can verify that by building OpenJDK with and without that option.

By 'stock' I just mean standard, pre-packaged (as opposed to ones you built yourself).

**Comment by David-Raccoon** [comment]
The reason for ```--with-extra-cflags='-Wno-deprecated-declarations'``` is to bypass the bug mentioned here: https://bugs.openjdk.org/browse/JDK-8202794. This bug is only fixed in JDK12, not in JDK11 (https://github.com/openjdk/jdk/commit/f4723253b68b53d3d1aba59313d53efa06e86a94). Therefore, currently I have no idea whether and how I can build JDK11 without  ```--with-extra-cflags='-Wno-deprecated-declarations'```.

(Above is what I've found so far. Sorry if I missed something.)

That said, this bug is about the use of ```readdir``` unix native library. Does it really matter to the use of reflection in application?

**Comment by steveblackburn** [comment]
I'm a little confused.

What I am saying is:

1. The bug you report does not arise in testing on any distributed JDK as far as I know.
2. We know that Wildfly uses deprecated reflection (an upstream issue I can't fix, also common to many other widely used applications)
3. We know that you used a particular flag when building your JDK that relates to treatment of deprecated declarations

Unless there is further information available, I conclude from the above that the behavior you're seeing is likely a result of the way you've built your JDK and is not a problem with DaCapo.  I recommend that you build the JDK without that flag to confirm this hypothesis.

**Comment by David-Raccoon** [comment]
Sorry about the unclearness. Basically, I'm having trouble with building JDK without that flag. At this point, I cannot confirm whether the problem can be fixed by removing this flag.

I'll report more information after I fix this JDK-build issue.

**Comment by caizixian** [comment]
@David-Raccoon Can you also try reproducing the problem with Temurin or other repackaged JDK?
I have seen such problems before, but only when using `-Xcomp -XX:-TieredCompilation` (#198)

**Comment by caizixian** [comment]
> The reason for `--with-extra-cflags='-Wno-deprecated-declarations'` is to bypass the bug mentioned here: https://bugs.openjdk.org/browse/JDK-8202794. This bug is only fixed in JDK12, not in JDK11 ([openjdk/jdk@f472325](https://github.com/openjdk/jdk/commit/f4723253b68b53d3d1aba59313d53efa06e86a94)). Therefore, currently I have no idea whether and how I can build JDK11 without `--with-extra-cflags='-Wno-deprecated-declarations'`.
> 
> (Above is what I've found so far. Sorry if I missed something.)
> 
> That said, this bug is about the use of `readdir` unix native library. Does it really matter to the use of reflection in application?

Also the JBS link you provided says it's been backported. If you want to build your own JDK 11, I strongly recommend that you use https://github.com/openjdk/jdk11u (if you are not doing so already) which receives continuous bug fixes, rather than using the tags in openjdk/jdk.

**Comment by David-Raccoon** [comment]
@caizixian Thanks for information about jdk11u. I've noticed that JDK-bug been resolved in this version of code, and it is built well without ```--with-extra-cflags='-Wno-deprecated-declarations'``` now. The JDK-built issue has been solved.

Unfortunately, the behavior is still the same as the previous one, that JVM dies silently after that warning.

**Comment by caizixian** [comment]
Could you run with Temurin https://adoptium.net/temurin/releases/?os=linux&arch=x64&package=jdk&version=11 so that we can confirm whether there's a problem with the JDK you built or your environment?

**Comment by David-Raccoon** [comment]
I've tested the JDK downloaded from the link you provided, using ```-Xcomp -XX:-TieredCompilation``` and results the same behavior.

Please check I'm using the correct version you mentioned.
```
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment Temurin-11.0.20.1+1 (build 11.0.20.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.20.1+1 (build 11.0.20.1+1, mixed mode)
```

**Comment by caizixian** [comment]
> I've tested the JDK downloaded from the link you provided, using `-Xcomp -XX:-TieredCompilation` and results the same behavior.
> 
> Please check I'm using the correct version you mentioned.
> 
> ```
> openjdk version "11.0.20.1" 2023-08-24
> OpenJDK Runtime Environment Temurin-11.0.20.1+1 (build 11.0.20.1+1)
> OpenJDK 64-Bit Server VM Temurin-11.0.20.1+1 (build 11.0.20.1+1, mixed mode)
> ```

Sorry for the confusion but please don't use `-Xcomp -XX:-TieredCompilation`, as it's known to be problematic (#198).

**Comment by caizixian** [comment]
@David-Raccoon What's the CPU model of the machine you were using?

**Comment by steveblackburn** [comment]
@David-Raccoon I believe the silent shutdown problem you observed was in fixed in 25fda5afa7630afbf3304eedb44325eecacd85c3

I'm closing this bug.  Please reopen if you can reproduce the bug on 25fda5afa7630afbf3304eedb44325eecacd85c3

**Comment by David-Raccoon** [comment]
Sorry for absense for few weeks.

@caizixian I'm using x64 CPU (Intel Xeon Gold 6338).
@steveblackburn Thanks! I'll check the fixed version.

**Comment by David-Raccoon** [comment]
I've test the new DaCapo-23.11-chopin release version on OpenJDK11u built from source https://github.com/openjdk/jdk11u, as suggested by @caizixian. But the silent shutdown problem still exists.
The JDK build configs:
```
./configure --with-target-bits=64 --with-debug-level=release
```
The Java commmand:
```
java -jar ../lib/dacapo-23.11-chopin.jar tradebeans
```
```
Using scaled threading model. 40 processors detected, 40 threads used to drive the workload, in a possible range of [1,2048]
Version: daytrader svn-1904225 wildfly 26.1.3.Final (use -p to print nominal benchmark stats)
DayTrader is using port 8080 (8080+0). Configure with -Djboss.http.port and/or -Djboss.socket.binding.port-offset
NOTE: Starting watchdog timer with timeout of 110 seconds. Adjust timeout with the -f command line option.
```
An observation is that is time of the process does not reaches 110 seconds to trigger time out.
